[SETTINGS]
# Comma-separated list of root directories to scan
root_folders = /home/jeff/retrogames/roms1, /home/jeff/retrogames/roms2, /home/jeff/retrogames/master_library

# The name of the output spreadsheet
output_file = rom_catalog.csv

#folders to skip
skip_folder = bios, Documents, Music, Movies, ports, images, tools, videos, artwork, manuals
